
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/lcone?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    fliter: stat
server:
  port: 8088
mybatis:
  type-aliases-package: com.demo.pojo
  mapper-locations: classpath:Mapper/*Mapper.xml


logging:
  level:
    com.demo.model.Mapper: debug
